services:
  - type: web
    name: boki-app
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # Renderが自動で安全なキーを生成
      - key: DATABASE_URL
        fromDatabase:
          name: boki-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
  
  - type: postgres # ★★★ "psql" から "postgres" に修正 ★★★
    name: boki-db
    plan: free
    